/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clientcode.bbclient.client;


import javax.swing.*;

import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;


public class BBClient {
    int TEAM;
    public String getGreeting() {
        return "Big Bertha has enterd the log... \r\n  Client initializing";
    }

    public static void main(String[] args) {
        BBClient bbc = new BBClient();
        bbc.runClient();
        System.out.println(bbc.getGreeting());


    }

    private void runClient(){
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    private void getTasbles(){
        //get the default instance of NetworkTables
        NetworkTableInstance inst = NetworkTableInstance.getDefault();
        //get a reference to the subtable called "datatable"
        NetworkTable datatable = inst.getTable("datatable"); 
        inst.startClientTeam(7475); 


    }
    
}
